### PR TITLE
Bump to 2.2.2

### PR DESCRIPTION
**Pull request by hadim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hadim** [comment]
@BrentDorsey @sugatoray, do you mind reviewing and merging this? This is currently blocking for a downstream package at https://github.com/conda-forge/aim-feedstock/pull/21

**Comment by sugatoray** [comment]
Thank you @hadim. If you would like to become a co-maintainer, please feel free to add yourself as a maintainer in the meta.yaml file and ping me then. 

The PR looks otherwise fine to me.

**Comment by hadim** [comment]
@sugatoray thanks, I think it's good to merge here.

**Comment by hadim** [comment]
(added myself as a maintainer)

**Pull request merged**
